name: CI/CD

on:
  push:
  pull_request:

env:
  NODE_VERSION: 14.x
  AWS_REGION : "eu-west-1"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: noi-techpark/github-actions/npm-test@v2
        with:
          test-command: npm run test:unit
          lint-enabled: false
          node-version: ${{env.NODE_VERSION}}

  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: deploy-test
    env:
      AWS_S3_BUCKET_NAME : "it.bz.beacon.webapp-test"
    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        env:
          X_VUE_APP_API_BASE_URL: "https://api.beacon.testingmachine.eu"
          X_VUE_APP_SUPPORT_EMAIL: "support@beacon.bz.it"

      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run build
          node-version: ${{env.NODE_VERSION}}

      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
        with:
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./dist

  deploy-prod:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/prod'
    needs: test
    concurrency: deploy-prod
    env:
      AWS_S3_BUCKET_NAME : "it.bz.beacon.webapp"
      SCRIPTS_HOST: 'https://scripts.opendatahub.com'
    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        env:
          X_VUE_APP_API_BASE_URL: "https://api.beacon.bz.it"
          X_VUE_APP_SUPPORT_EMAIL: "support@beacon.bz.it"


      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run build
          node-version: ${{env.NODE_VERSION}}

      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
        with:
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./dist
